### ISSUE TITLE
Project Dead?

### ISSUE THREAD

**Issue by alpha01** [fastly/libvmod-urlcode#12]
Is this vmod no longer maintained? Last change was over four years ago, and the module now fails to build on newer versions of Varnish.

**Comment by nigoroll** [comment]
since varnish 5.1, this vmod is somehow superseded by vmod_blob http://varnish-cache.org/docs/trunk/reference/vmod_generated.html#func-transcode - which is more generic and includes the functionality of this vmod

**Comment by alpha01** [comment]
Awesome, good to know. Thanks!
